repos:
  "microsoft/vscode":
    pattern: "^[A-Za-z]+ [0-9]+$"
  "facebook/react":
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+"

mail:
  host: "your.smtp.host"
  port: 587
  secure: false # Set to true if your SMTP server uses SSL/TLS
  auth:
    user: "your-email@example.com"
    pass: "your-email-password"
  from: "your-email@example.com"
  to: "recipient-email@example.com"

jsonFilePath: data/releases.json
